apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-prometheus-rules
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
data:
  alerting_rules.yml: |
    groups:
      - name: alerting_rules
        rules:
          - alert: HighPodRestart
            expr: rate(kube_pod_container_status_restarts_total[5m]) * 60 > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Pod {{`{{ $labels.pod }}`}} is restarting frequently"
  recording_rules.yml: |
    groups:
      - name: recording_rules
        rules:
          - record: job:http_inprogress_requests:sum
            expr: sum by (job) (http_inprogress_requests)